### ISSUE TITLE
Is it possible to use it in single cell long read RNA-seq data?

### ISSUE THREAD

**Issue by WestLakeliushuli** [statgen/popscle#73]
I've tried using popscle or demuxlet only to run the single cell long read RNA-seq. I found no matter what the size of input bam or vcfs, and no matter how I increased the memory (like to 400G), it always threw "oom-kill". So, is the popscle or demuxlet cannot deal with LR RNA-seq data?

**Comment by hyunminkang** [comment]
There are two possibilities. 

(1) The number of variants you are using might be too many. Try reducing the number of variants and see if it works first.

(2) We have not tested demuxlet on long read RNAs, so there can be certain features in your BAM that incurs excessive memory use, but I don't have a good way to tell you what the reason is.

If you provide me a reproducible example, I can look into it.

**Comment by WestLakeliushuli** [comment]
Hi hyunminkang,

Thanks for your quick response. I've sent you the link to the example data via email.  The bam file is generated by minimap2, and the tag-group and tag-UMI were added using a custom script (I don't know if it's also an issue too).

**Comment by WestLakeliushuli** [comment]
I removed records with extremely long reads (like more than 50kb), and it works now.
